### ISSUE TITLE
Add user permissions, read-only by default 

### ISSUE THREAD

**Issue by scroot** [emad-elsaid/xlog#10]
Whether to add user permissions , And it is read-only by default. 
Otherwise, only watch it myself

**Comment by emad-elsaid** [comment]
I'm not sure I understand. but I was thinking of the following:
- if the filesystem is readyonly for the current user we can hide the edit options. 
- this probably involve adding method to `Page#IsReadOnly` struct to return false if readonly and all extensions and views can use that to hide any edit feature.

**Comment by emad-elsaid** [comment]
I added a CLI flat `--readonly` which will remove any feature that writes to the desk. also I used that to add another flag `--build=dest/dir` to build all pages to destination directory to use as static website. I'm preparing to move to xlog instead of jekyll for my blog. still
