### ISSUE TITLE
side by side edit / preview

### ISSUE THREAD

**Issue by gedw99** [emad-elsaid/xlog#11]
I was wondering what you think of the idea of side by side editing ?

you have the markdown editor on the left and the result / preview on the right.
It makes it easier when you creating content. At least for me.

**Comment by gedw99** [comment]
actually have you seen he GIO Markdown editor ?
https://github.com/gioui/gio-example/tree/main/markdown

If we used this as a basis we could extend it to allow users to easily add heading, text, images via a menu. A bit like how google docs works. My intention is to make xlog really easy for non technical users to make notes with, because many of them dont know the markup syntax.

I know it will make the GUI larger because it will need be wasm... But maybe its a worthy idea to make it easier for users and easier for golang devs to extend it.

**Comment by emad-elsaid** [comment]
this sounds like a good idea, sorry I haven't seen this issue earlier. but yeah, I remember that the JS editor I'm using for markdown can have preview! I changed it too many times that I don't remember if it's this one or another editor.

**Comment by emad-elsaid** [comment]
I thought about this idea more, I don't think it's for me, I believe the side by side editing is distracting. I prefer to have distraction free edit page with just the editor as much as possible. so I won't work on this feature but If someone wan't to add it behind some feature switch (cli flag). I'm ok with it
