### ISSUE TITLE
[feature] Adding Disqus or GitHub comments to the static website?

### ISSUE THREAD

**Issue by salehmu** [emad-elsaid/xlog#15]
Title. Also, this should be optional; so xlog can make use of some configuration file or a settings page(?).

**Comment by emad-elsaid** [comment]
This is a good idea. and implementing it would be simple:

- add an extension folder
- import the extension in `cmd/xlog/xlog.go`
- add flag for disqus config or github comments
- add a widget after view to render the comments if the flag is set

I have time today I'll try to work on it

**Comment by emad-elsaid** [comment]
That didn't take much too much time to code. 

https://github.com/emad-elsaid/xlog/commit/61381b3bdc9c269030780ce27e892e7f42ca4cc2

would you like to do the GitHub comments extension? 

![Screenshot-2023-01-02_10-25-32](https://user-images.githubusercontent.com/54403/210213451-ffe09288-cc13-45fd-817c-eb4c9453c134.png)

**Comment by salehmu** [comment]
Excellent. Yes, I'd love to.

**Comment by salehmu** [comment]
Certainly, but my timeline is over-occupied recently. If you are up for it, do it please


Jan 5, 2023, 17:13 by ***@***.***:
