### ISSUE TITLE
Allow users to write custom css

### ISSUE THREAD

**Issue by mohamedelhefni** [emad-elsaid/xlog#24]
add `custom_css` extension that allows user to add custom css snippets and store them

**Comment by emad-elsaid** [comment]
right now overwriting the css can be done with having `/public/style.css` file in the served directory. 

Adding custom CSS in addition to the default style is a good idea. I'm open for it. here is how I think can be done: 

- add extension `custom_css` as you said
- adds a flag for CSS file that needs to be added to the header
- register a `head_widget` to add the `<link rel="stylesheet" href="flag-value-here">` in case the flag is set.
