### ISSUE TITLE
Dark theme seems broken and wrong links in readme.md

### ISSUE THREAD

**Issue by conradax** [emad-elsaid/xlog#26]
In dark mode:
* caret is not visible when editing
  It's almost the same color as background and can't see it blinking
* footer element is white (class "has-background-white")

Platform: `Firefox 109.0.1` and `Chromium 108.0.5359.125`
![image](https://user-images.githubusercontent.com/20236946/216810812-634f5080-eabe-4a03-b57a-60b6bfbf0358.png)

-----------------------------------------------

And link seems not correct in the [readme.md](https://raw.githubusercontent.com/emad-elsaid/xlog/master/README.md):
* In Section `Documentation`: 
   `Generating static site` and `Overriding Asstes` are linked to `localhost:3000`

I think it supposed to be something like this: https://xlog.emadelsaid.com/Assets/

![image](https://user-images.githubusercontent.com/20236946/216811691-f76e5cce-61da-4144-b8e1-7ab0fae2bdd4.png)

**Comment by emad-elsaid** [comment]
Hi @conradax thanks for opening the issue, I corrected the readme issue.

The crate issue may take a bit of time, I have some time today I may work on it. but feel free to contribute a fix

**Comment by emad-elsaid** [comment]
fixed the cursor color and width to be more visible in both light and dark theme. 
![Screenshot-2023-02-05_12-48-18](https://user-images.githubusercontent.com/54403/216816911-98bede26-c994-4307-917e-5c7f7fb6c5b4.png)
![Screenshot-2023-02-05_12-48-38](https://user-images.githubusercontent.com/54403/216816933-fd1176d1-ecbc-42a7-8532-0b59563d371e.png)

and released version 76 
https://github.com/emad-elsaid/xlog/releases/tag/v0.76.0
