### ISSUE TITLE
bug: "Edit on github" in gui  on works on index page only ?

### ISSUE THREAD

**Issue by gedw99** [emad-elsaid/xlog#32]
It seems on the index page works from the browser.  All others fail to connect to the markdown page on github.

failure case:

for example https://xlog.emadelsaid.com/digital%20gardening/

then clock "edit on github" and you go to 404

---

success case:

https://xlog.emadelsaid.com/

then clock "edit on github" and you go to correct github page.

**Comment by emad-elsaid** [comment]
thanks for the report. I think this is because in this repository I'm rendering the `/docs` directory and the link points to a file under the `/`. I need to improve the `github` extension to take a path with a pattern instead of the repository URL.

**Comment by gedw99** [comment]
thanks @emad-elsaid 

is fixed for me too.
