### ISSUE TITLE
Docs website is not reachable

### ISSUE THREAD

**Issue by ProvoK** [emad-elsaid/xlog#35]
Since a couple of days, the docs site (https://xlog.emadelsaid.com/) is apparently "down" (more probably a DNS misconfiguration)
<img width="770" alt="image" src="https://github.com/emad-elsaid/xlog/assets/6241450/7ee8f1a7-4aa6-4517-842a-88c1a3f2554f">

It would be nice to have it online 😄

**Comment by emad-elsaid** [comment]
thanks for reporting it, I think I may have removed the DNS record by mistake when I was migrating to a new server. now it's back
