### ISSUE TITLE
downgrade to go 1.20.12

### ISSUE THREAD

**Issue by tooolbox** [emad-elsaid/xlog#57]
This is a very cool project and I'm considering using it for a knowledge base I want to put togther.

However, I'm working with some very old Windows machines, a la Windows 7, and it crashes on startup since Go no longer supports that OS.

I'm wondering if it would be possible for you to to downgrade the project to using go 1.20.12 since it still supports Windows 7, unless you are actively using features in the latest versions of Go?

Ref: https://github.com/golang/go/issues/64622

Minor Edit: If this were feasible, I would also request that you downgrade the version of Go used to build the release artifacts.

**Comment by tooolbox** [comment]
Looking into this further, it appears that the dependencies https://github.com/emad-elsaid/memoize and https://github.com/emad-elsaid/types are also both marked as 1.22.  Barriers to downgrading present in memoize, types and xlog include:
- Use of `log/slog` (which can be [shimmed](https://github.com/sagikazarmark/slog-shim)) 
- `sync.OnceFunc/Value/Values` (convenience functions which could be shimmed)
- The http.Request.PathValue which again is possible to downgrade to the previous implementation in xlog
- Some generics issues which I am not immediately sure what to do with.  Error message about casting an LRU into a hashicorp.LRU or some such, still looking into it.

Not terrible, but not as simple as I originally thought.

**Comment by emad-elsaid** [comment]
It would be possible, but maintaining this promise of using 1.20 in the future will be hard. I try to update dependencies all the time to make sure the project doesn't fall behind on any optimizations new Go versions has or new features. but feel free to work on that.

**Comment by Darthagnon** [comment]
Go v1.21.4 should also work on Windows 7 / Server 2008, or [VxKex](https://github.com/vxiiduu/VxKex/) can be used to allow Go software v1.21.5+ (e.g. v1.22) on Win7.

**Comment by tooolbox** [comment]
Interesting, I will give VxKex a try, thank you.
